FB_APP_ID = "GET_FROM_FACEBOOK_DEVELOPER_GRAPH_API_EXPLORER"
FB_APP_SECRET = "GET_FROM_FACEBOOK_DEVELOPER_GRAPH_API_EXPLORER"
FB_PAGE_ID = "GET_FROM_FACEBOOK_DEVELOPER_GRAPH_API_EXPLORER"
FB_USER_SHORT_TOKEN = "GET_FROM_FACEBOOK_DEVELOPER_GRAPH_API_EXPLORER"
FB_GRAPH_API_VERSION = "3.0"
STORED_VIDEO_JSON_FILE = "uploaded_videos.json"
JSON_VIDEO_ID_KEY = "video_ids"
VIDEO_FOLDER = "videos/"

# Create a telegram app and get the below details from https://my.telegram.org/apps.
TELEGRAM_API_ID = 'GET_FROM_TELEGRAM_APP_BOT'
TELEGRAM_API_HASH = 'GET_FROM_TELEGRAM_APP_BOT'
TELEGRAM_BOT_TOKEN = 'GET_FROM_TELEGRAM_APP_BOT'
CHAT_ID = ['GET_FROM_TELEGRAM_APP_BOT'] # get chat id using https://api.telegram.org/bot<BOT_API_TOKEN>/getUpdates